### ISSUE TITLE
Update the CHANGELOG (keep this issue open)

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#125]
### Descriptive summary

Even though we are far away from our first release, I'd like to start a /CHANGELOG.md that gets updated at the end of each sprint.  It will help us better track the features we're implementing.

**Comment by scherztc** [comment]
Closed issues with feature or bug.

**Comment by scherztc** [comment]
.7 ??????? 

Update to hyrax 2.2.1
render 404 error instead of template
Update collection_form by removing specific fields and modifing
set max sidekiq retries to 3
add hyrax citations view partial override
add hyrax partial override _form_files
hide browse everything on batch create
Set footer elements
fix collection license persistence
add mendeley meta-tags
make toolbar links match sidebar
get original filename for box files
handle slashes in paths for riiif
fix etd type field persistence
add noid initializer
add batch upload
Change Etd publisher field to single value
Fix managed works title wrapping
Update Spanish and Mandarin translations 
Resolves bug that shows department field incorrectly.
Change flash message wording.
Disable collection export
Fixes owner file permission problem with proxy deposit.
Show ETD committee members on work show page
Make session and login cookies secure on production
Add a What's New page for 4.0
Hide remaining Collection Export links
Refactor code that defaults new collections to Open Access
