### ISSUE TITLE
The db:seed rake task needs fixin

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#151]
### Descriptive summary

I noticed a couple of problems with the recently added `rake db:seed` task:

1) The works that are generated are not assigned an admin set.  This leads to problems when the owner tries to do something with the work.  All works should be assigned to the default admin set.

2) The generated admin user didn't have admin privileges when I tried it.  So something is broken there.

**Comment by jayanthdeejay** [comment]
* We probably have to [create](https://github.com/samvera/hyrax#create-default-administrative-set) the default admin set before we could create the admin role as the Hyrax's workflows need to be loaded into the application there by any new works that are added to the application are assigned the default admin set.

* Since the create admin role happens to run when we create the default admin set, changing the line `admin = Role.create(name: 'admin')` to `admin = Role.find_or_create_by!(name: 'admin')` indeed assigns the admin role to the user 'admin@exmaple.com' during the seed task. 

* I still need to figure out why the application breaks when the admin user tries to edit/do something with the work that was created during the seed task.

**Comment by hortongn** [comment]
These issues have been resolved
