### ISSUE TITLE
Scholar Curly and Dev RIIIF

### ISSUE THREAD

**Issue by bsp3ars** [uclibs/ucrate#775]
Riiif on Curly and Dev are both having issues. Derivatives work, but Riiif doesn't find the image. We know that the folder that the files should be put in hasn't been touched since late 2018.

**Comment by scherztc** [comment]
Started GET "/images/t435gc96m%252Ffiles%252F5c097253-7f4e-4263-bcc0-63a688a96a41/info.json" for 172.30.229.116 at 2020-02-27 10:07:29 -0500
Cannot render console from 172.30.229.116! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by Riiif::ImagesController#info as JSON
  Parameters: {"model"=>"riiif/image", "id"=>"t435gc96m%2Ffiles%2F5c097253-7f4e-4263-bcc0-63a688a96a41"}
Invalid characters in id `t435gc96m%2Ffiles%2F5c097253-7f4e-4263-bcc0-63a688a96a41`
Completed 404 Not Found in 25ms (ActiveRecord: 0.0ms)

Riiif::ImageNotFoundError (Riiif::ImageNotFoundError):

This is due to the passenger.conf setting that did not got reset or did not get set when we did a capiastrano deploy.

**Comment by scherztc** [comment]
https://github.com/uclibs/scholar_uc_legacy/issues/1581
https://github.com/uclibs/scholar_uc_legacy/pull/1578
https://github.com/uclibs/scholar_uc_legacy/issues/1537

**Comment by scherztc** [comment]
Curly is GOOD.  I think the key is that the rails server and the sidekiq services be running in production mode.

**Comment by scherztc** [comment]
Scholar_DEV is GOOD.  Using this for SideKiq : bundle exec sidekiq -d -c 1 -q ingest -q default -q event -q change -L log/sidekiq.log -C config/sidekiq.yml -e production

**Comment by scherztc** [comment]
It is important the sidekiq be started in production mode even on DEV and CURLY.

**Comment by scherztc** [comment]
Also make sure this is in your development.rb

# Disable serving static files from the `/public` folder by default since
  # Apache or NGINX already handles this.
  config.public_file_server.enabled = true
